class User
  include Mongoid::Document

  devise :database_authenticatable, :registerable, # :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :authentication_keys => [:username]

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Token authenticatable
  field :authentication_token, :type => String
  before_save :ensure_authentication_token

  field :username

  embeds_many :drawings, as: :drawable
  embeds_many :missions

  def self.create_from_email(email)
      username = User.generate_name
      while User.where(username: username).exists? do username = User.generate_name end

      return User.new(username: username, password: User.generate_password, email: email)
  end

  def self.generate_name
    adjectives = [
      'awesome',
      'amazing',
      'short',
      'tall',
      'slim',
      'cheerful',
      'jolly',
      'dangerous',
      'old',
      'young',
      'invisible',
      'gigantic',
      'fearful',
      'brave',
      'sharp',
      'smart',
      'clever',
      'fluffy',
      'handsome',
      'beautiful',
      'pretty',
      'night',
      'sunset',
      'dusk',
      'dawn',
      'sunrise',
      'winter',
      'spring',
      'joyful',
      'fast',
      'slow',
      'playful',
      'musical',
      'singing',
      'dancing',
      'mysterious',
      'jumping',
      'bearded',
      'blue',
      'red',
      'orange',
      'green',
      'brown',
      'black',
      'white',
      'grey',
      'pink',
      'yellow',
      'purple',
      'automatic',
      'circular',
      'bilingual',
      'teleporting',
      'delighted',
      'glad',
      'electrical',
      'round',
      'squared',
      'flying',
      'crawling',
      'whistling',
      'howling',
      'water',
      'underwater',
      'ninja',
      'rocking',
      'robot',
      'marvellous',
      'creative',
      'writing',
      'wise',
      'careful',
      'heroic',
      'smiling',
      'winning',
      'planning',
      'hopping',
      'chuckling',
      'sizzling',
      'wobbling',
      'reliable',
      'sensible',
      'responsible',
      'humble',
      'recalling',
      'unlucky',
      'lucky',
      'unseen',
      'frosting',
      'freezing',
      'messy',
      'tidy',
      'pleasant',
      'big',
      'bigger',
      'biggest',
      'happy',
      'happier',
      'happiest',
      'hot',
      'hotter',
      'hottest',
      'chilly',
      'chillier',
      'chilliest',
      'thin',
      'thinner',
      'thinnest',
      'funny',
      'funnier',
      'funniest',
      'fat',
      'fatter',
      'fattest',
      'crazy',
      'crazier',
      'craziest',
      'lucky',
      'luckier',
      'luckiest',
      'lazy',
      'hazy',
      'crispy',
      'fussy',
      'great',
      'greater',
      'greatest',
      'grand',
      'wishful',
      'fearless',
      'hopeful',
      'proud',
      'giant'
    ]

    # http://en.wikipedia.org/wiki/List_of_animal_names
    animals = [
      'Aardvark',
      'Albatross',
      'Alligator',
      'Alpaca',
      'Ant',
      'Anteater',
      'Antelope',
      'Ape',
      'Armadillo',
      'Donkey',
      'Baboon',
      'Badger',
      'Barracuda',
      'Bat',
      'Bear',
      'Beaver',
      'Bee',
      'Bison',
      'Boar',
      'Buffalo',
      'Butterfly',
      'Camel',
      'Caribou',
      'Cat',
      'Caterpillar',
      'Cattle',
      'Chamois',
      'Cheetah',
      'Chicken',
      'Chimpanzee',
      'Chinchilla',
      'Clam',
      'Cobra',
      'Cod',
      'Cormorant',
      'Coyote',
      'Crab',
      'Crane',
      'Crocodile',
      'Crow',
      'Deer',
      'Dinosaur',
      'Dog',
      'Dogfish',
      'Dolphin',
      'Donkey',
      'Dove',
      'Dragonfly',
      'Duck',
      'Dugong',
      'Eagle',
      'Echidna',
      'Eel',
      'Eland',
      'Elephant',
      'Elk',
      'Emu',
      'Falcon',
      'Ferret',
      'Finch',
      'Fish',
      'Fly',
      'Fox',
      'Frog',
      'Gaur',
      'Gazelle',
      'Gerbil',
      'Giraffe',
      'Gnat',
      'Gnu',
      'Goat',
      'Goose',
      'Gopher',
      'Gorilla',
      'Grasshopper',
      'Grouse',
      'Guanaco',
      'Gull',
      'Hamster',
      'Hare',
      'Hawk',
      'Hedgehog',
      'Heron',
      'Hippopotamus',
      'Hornet',
      'Horse',
      'Human',
      'Hummingbird',
      'Hyena',
      'Iguana',
      'Jackal',
      'Jaguar',
      'Jellyfish',
      'Kangaroo',
      'Koala',
      'Dragon',
      'Kouprey',
      'Kudu',
      'Lark',
      'Lemur',
      'Leopard',
      'Lion',
      'Llama',
      'Lobster',
      'Locust',
      'Loris',
      'Louse',
      'Lyrebird',
      'Magpie',
      'Mallard',
      'Manatee',
      'Meerkat',
      'Mink',
      'Mole',
      'Monkey',
      'Moose',
      'Mouse',
      'Mosquito',
      'Mule',
      'Narwhal',
      'Newt',
      'Nightingale',
      'Octopus',
      'Okapi',
      'Opossum',
      'Oryx',
      'Ostrich',
      'Otter',
      'Owl',
      'Ox',
      'Oyster',
      'Panda',
      'Panther',
      'Parrot',
      'Partridge',
      'Peafowl',
      'Pelican',
      'Penguin',
      'Pig',
      'Pigeon',
      'Platypus',
      'Pony',
      'Porcupine',
      'Porpoise',
      'Quelea',
      'Rabbit',
      'Raccoon',
      'Rail',
      'Ram',
      'Rat',
      'Raven',
      'Reindeer',
      'Rhinoceros',
      'Rook',
      'Salamander',
      'Sea',
      'Seahorse',
      'Seal',
      'Seastar',
      'Serval',
      'Shark',
      'Sheep',
      'Shrew',
      'Skunk',
      'Snail',
      'Snake',
      'Spider',
      'Squid',
      'Squirrel',
      'Stinkbug',
      'Swallow',
      'Swan',
      'Tapir',
      'Tarsier',
      'Termite',
      'Tiger',
      'Toad',
      'Trout',
      'Turkey',
      'Turtle',
      'Wallaby',
      'Walrus',
      'Wasp',
      'Weasel',
      'Whale',
      'Wolf',
      'Wombat',
      'Woodpecker',
      'Worm',
      'Wren',
      'Yak',
      'Zebra',
    ]

    first_animal = animals.sample
    second_animal = animals.sample

    return adjectives.sample.capitalize + (if first_animal.length < 6 then first_animal else first_animal[0..(first_animal.length/2).floor] end) + (if second_animal.length < 6 then second_animal.downcase else second_animal[(second_animal.length/2).floor..-1] end)

  end

  def self.generate_password
    words = [
      'absorbed',
      'according',
      'accuracy',
      'actually',
      'advantage',
      'advertise',
      'almost',
      'amongst',
      'anchors',
      'apprehensive',
      'approximately',
      'arrived',
      'attempts',
      'audience',
      'available',
      'aware',
      'beautiful',
      'before',
      'beginning',
      'believe',
      'between',
      'biggest',
      'bodies',
      'breeze',
      'building',
      'camped',
      'capable',
      'carefully',
      'carriages',
      'carried',
      'castles',
      'centre',
      'century',
      'challenging',
      'change',
      'cities',
      'climbing',
      'colourful',
      'common',
      'complete',
      'completion',
      'countryside',
      'crawl',
      'creatures',
      'crept',
      'delivered',
      'designed',
      'destination',
      'destructive',
      'developed',
      'different',
      'difficult',
      'digital',
      'direction',
      'disappeared',
      'disease',
      'disguised',
      'disturbed',
      'echoed',
      'effortless',
      'emergency',
      'encounter',
      'encourage',
      'engines',
      'ensure',
      'environment',
      'escaping',
      'essential',
      'excellent',
      'excited',
      'exciting',
      'expensive',
      'extinguishing',
      'extremely',
      'families',
      'festival',
      'fighting',
      'finished',
      'first',
      'follow',
      'foundations',
      'frequently',
      'future',
      'generally',
      'generation',
      'gently',
      'gingerly',
      'gleaming',
      'grabbed',
      'gradually',
      'headquarters',
      'healthy',
      'heard',
      'hedges',
      'highly',
      'hopeful',
      'illuminated',
      'important',
      'importantly',
      'including',
      'individual',
      'injured',
      'injured',
      'inspecting',
      'interesting',
      'invention',
      'involved',
      'journey',
      'judged',
      'knowledge',
      'known',
      'largest',
      'material',
      'medicine',
      'million',
      'moment',
      'most',
      'moving',
      'mysterious',
      'nastiest',
      'necessary',
      'noisy',
      'notice',
      'occurred',
      'opposite',
      'original',
      'participate',
      'particularly',
      'passenger',
      'perfectly',
      'perform',
      'physical',
      'physically',
      'pieces',
      'pierce',
      'planned',
      'planning',
      'pollution',
      'practice',
      'preserve',
      'press',
      'prevent',
      'process',
      'produce',
      'properties',
      'purpose',
      'qualified',
      'question',
      'raising',
      'ready',
      'realistic',
      'regardless',
      'rehearsed',
      'release',
      'released',
      'remained',
      'remember',
      'replaced',
      'required',
      'satisfied',
      'selects',
      'serious',
      'shook',
      'should',
      'silence',
      'slipped',
      'slippery',
      'smoothly',
      'sneeze',
      'special',
      'sprawling',
      'spreading',
      'still',
      'stopped',
      'stopping',
      'strength',
      'stretched',
      'stripes',
      'structures',
      'successful',
      'sunny',
      'supply',
      'surprise',
      'surprising',
      'survive',
      'swimming',
      'symbol',
      'tallest',
      'technique',
      'themselves',
      'thoroughly',
      'throughout',
      'together',
      'top',
      'transformed',
      'transported',
      'trapped',
      'tumble',
      'uncoiled',
      'unusual',
      'vanishing',
      'varieties',
      'visitors',
      'washing',
      'weight',
      'where',
      'widest',
      'wonderful',
      'wrestling',
    ]

    return words.sample.capitalize + words.sample.capitalize + rand(999).to_s
  end
end
